demo3/Foods/urls.py
from django.conf.urls import url
from . import views
app_name = "food"
urlpatterns = [

    url(r'^blog/$', views.blog, name="blog"),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^gallery/$', views.gallery, name="gallery"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name="register"),
    url(r'^single/$', views.single, name="single"),
    url(r'^menu/$', views.menu, name="menu"),
    url(r'^index/$', views.index, name="index"),
    url(r'^text/$', views.text, name="text"),
    url(r'^error/$', views.error, name="error"),


]

demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('Foods/', include('Foods.urls', namespace='food')),
]

demo3/Foods/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=20, null=False,)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username

    class Meta():
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Title(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "标题"
        verbose_name_plural = verbose_name


class Body(models.Model):
    title = models.CharField(max_length=20)
    littletitle = models.CharField(max_length=20)
    body = models.CharField(max_length=200,null=True)
    littlebody = models.CharField(max_length=100,null=True)
    img = models.ImageField()
    price = models.IntegerField(default=0,null=True)
    date = models.DateTimeField(auto_now_add=True,null=True)
    fo_id = models.ForeignKey(Title, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "内容"
        verbose_name_plural = verbose_name


class People(models.Model):
    name = models.CharField(max_length=20)
    skill = models.CharField(max_length=50)
    jianjie = models.CharField(max_length=200)
    fo_id = models.ForeignKey(Title, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "人物"
        verbose_name_plural = verbose_name


class AddImg(models.Model):
    img = models.ImageField(upload_to="imgs")
    desc = models.CharField(max_length=20)

    def __str__(self):
        return self.desc

    class Meta():
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name


class Subject(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField()
    sub = models.CharField(max_length=50)
    detal = models.CharField(max_length=500)

    def __str__(self):
        return self.username

    class Meta():
        verbose_name = "建议"
        verbose_name_plural = verbose_name


class Shop(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    img = models.ImageField()
    num = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True,verbose_name="时间")

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "商品"
        verbose_name_plural = verbose_name


class Style(models.Model):
    img = models.ImageField()
    name = models.CharField(default=" ", max_length=10)
    body = models.CharField(default=" ", max_length=50)

    def __str__(self):
        return self.img

    class Meta():
        verbose_name = "样式"
        verbose_name_plural = verbose_name


class Cook(models.Model):
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=500)
    img = models.ImageField()
    contact = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "厨师"
        verbose_name_plural = verbose_name


class Hero(models.Model):
    name = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=500)
    img = models.ImageField()

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "荣誉"
        verbose_name_plural = verbose_name


class Log(models.Model):
    create_time = models.DateTimeField(auto_now_add=True)
    place = models.CharField(max_length=50)
    deeds = models.CharField(max_length=200)
    img = models.ImageField()
    img2 = models.CharField(max_length=20)

    def __str__(self):
        return self.place

    class Meta():
        verbose_name = "记录"
        verbose_name_plural = verbose_name

demo3/Foods/views.py
from django.shortcuts import render,redirect,reverse
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import *

# Create your views here.
def about(request):
    msg = Cook.objects.all()
    temp = Body.objects.all()
    return render(request,"about.html",locals())


def blog(request):
    return render(request,"blog.html")


def contact(request):
    if request.method == "POST":
        x = Subject()
        x.username = request.session["username"]
        x.email = request.POST.get("Email")
        x.sub = request.POST.get("Subject")
        x.detal = request.POST.get("Detail")
        x.save()
        return render(request, "contact.html", {"msg": "提交成功"})
    else:
        return render(request, "contact.html")
def gallery(request):
    return render(request,"gallery.html")


def menu(request):
    temp1 = Shop.objects.all().order_by("-num")[:4]
    temp2 = Shop.objects.all().order_by("-date")[:4]
    temp = Style.objects.all()
    # paginator = Paginator(temp, 1)
    #     # page = paginator.get_page(1)
    return render(request, "menu.html",locals())


def index(request):
    temp1 = Shop.objects.all().order_by("-num")[:4]
    temp2 = Shop.objects.all().order_by("-date")[:4]
    temp3 = Style.objects.all()
    msg = Body.objects.all()
    hero = Hero.objects.all()[1:3]
    log = Log.objects.dates(field_name="create_time", kind="month", order='DESC')

    return render(request, "index.html", locals())


def login(request):
    if request.method == "GET":
        return render(request,"login.html")
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")
        # print(username,password)
        try:
            user = User.objects.get(username=username)
            # if user.username != username:
            #     return render(request, "register.html", {"msg": "用户名不存在，请注册"})
            if user.password != password:
                return render(request, "login.html", {"msg": "密码错误"})
            else:
                request.session["username"] = username
                res = redirect(reverse('food:index'))
                return res
            # return redirect(reverse('food:index'))
        except Exception as e:
            print("错误信息",e)
            return render(request, "login.html", {"msg": "用户名或密码错误,或未注册，请注册"})


def register(request):
    if request.method == "GET":
        return render(request,"register.html")
    else:
        username = request.POST.get("username").strip()
        password = request.POST.get("password").strip()
        password2 = request.POST.get("password2").strip()

        # 用户名不能为空
        if username == " " or username == None:
            return render(request, "register.html", {"msg": "用户名不能为空"})
        # 判断密码是否小于6位
        if len(password) < 6:
            return render(request, "register.html", {"msg": "密码不能小于6位，请重新输入"})
        # 判断密码是否一致
        if password != password2:
            return render(request, "register.html", {"msg": "两次密码不一致"})
        # 用户名是否存在
        user = User.objects.filter(username=username)
        if len(user) > 0:
            return render(request, "register.html", {"msg": "用户名已存在，请重新输入"})

        # 添加用户
        try:
            user = User(username=username, password=password)
            user.save()
            return redirect(reverse('food:login'))
        except Exception as e:
            print("添加出错，错误信息是：", e)
            return render(request, "register.html", {"msg": "注册失败，请重新注册"})



def single(request):
    return render(request,"single.html")


def logout(request):
    res = redirect(reverse('food:index'))
    request.session.flush()
    return res


def text(request):
    msg = "您尚未登录，请登录"
    return render(request, "login.html",{"msg": msg})


def error(request):
    return render(request,"404.html")

demo3/templates/about.html
{% extends 'base.html' %}
{% block top %}
<div class="banner-inner"></div>
{% endblock %}
{% block body %}
	<!--/main-->
{% for i in temp %}
	<section class="banner-bottom">
		<div class="container">
			<h3 class="tittle">{{ i.title }}</h3>
			<div class="row inner-sec">
				<div class="col-lg-6 about-img" data-aos="flip-right">
					<img src="/static/images/{{ i.img }}" class="img-fluid" alt="">
				</div>
				<div class="col-lg-6 about-info text-left" data-aos="flip-left" >
					<h4 class="sub-hd mb-4">{{ i.littletitle }} </h4>
					<p>{{ i.body }}</p>
					<div class="view my-4">
						<a href="{% url 'food:error' %}" class="btn btn-primary read-m">View More</a>
					</div>

					<!--<img src="/static/images/{{ i.img }}" class="img-fluid" alt="">-->
				</div>
			</div>
		</div>
	</section>
{% endfor %}
	<!--/seller-->
	<section class="grid-info-section">
		<div class="container">
			<h3 class="tittle">Best Smile</h3>
			<div class="row inner-sec">
				<ul id="flexiselDemo1">
					<li>
						<div class="blog-item text-center">
							<img src="/static/images/1.jpg" alt=" " class="img-fluid rounded-circle" />
							<div class="floods-text">
								<h3>Item 1</h3>

							</div>
						</div>
					</li>
					<li>
						<div class="blog-item text-center">
							<img src="/static/images/2.jpg" alt=" " class="img-fluid rounded-circle" />
							<div class="floods-text">
								<h3>Item 2</h3>

							</div>
						</div>
					</li>
					<li>
						<div class="blog-item text-center">
							<img src="/static/images/3.jpg" alt=" " class="img-fluid rounded-circle" />
							<div class="floods-text">
								<h3>Item 3</h3>
							</div>
						</div>
					</li>
					<li>
						<div class="blog-item text-center">
							<img src="/static/images/4.jpg" alt=" " class="img-fluid rounded-circle" />
							<div class="floods-text">
								<h3>Item 4</h3>
							</div>
						</div>
					</li>
					<li>
						<div class="blog-item text-center">
							<img src="/static/images/5.jpg" alt=" " class="img-fluid rounded-circle" />
							<div class="floods-text">
								<h3>Item 5</h3>

							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</section>
	<!--//seller-->
	<section class="banner-bottom">
		<div class="container-fluid">
			<h3 class="tittle">我们的实力</h3>
			<div class="row inner-sec team-sec">
				{% for i in msg %}
				<div class="col-md-6 team-main">
					<div class="row">
						
						<div class="col-md-5 team-img" data-aos="flip-right">
								<img src="/static/images/{{ i.img }}" alt=" " class="img-fluid" />
						</div>
						<div class="col-md-7 team-info text-left" data-aos="flip-left">
								<h4>{{ i.name }} </h4>
								<h6>{{ i.title }}</h6>
								<p>{{ i.body }} </p>
								<div class="row  pt-3 mt-3 team-social border-top">
									<h5 class="col-md-4 text-left">{{ i.contact }}</h5>
									<ul class="col-md-8 social_list1 text-right">

										<li>
											<a href="#" class="facebook1 ">
												<i class="fab fa-facebook-f"></i>
				
											</a>
										</li>
										<li>
											<a href="#" class="twitter2 mx-2">
												<i class="fab fa-twitter"></i>
				
											</a>
										</li>
										<li>
											<a href="#" class="dribble3">
												<i class="fab fa-dribbble"></i>
											</a>
										</li>
										
									</ul>
								</div>
						</div>
					</div>

				</div>
				{% endfor %}
			</div>
		</div>
	</section>

	<!--//main-->
{% endblock %}

demo3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <title>{% block title %} {% endblock %}</title>
    <title> Register</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="/static/css/bootstrap.css" rel='stylesheet' type='text/css' />
	<link href="/static/css/contact.css" rel='stylesheet' type='text/css' />
	<link href="/static/css/style.css" rel='stylesheet' type='text/css' />
	<link href="/static/css/fontawesome-all.css" rel="stylesheet">
	<script src="/static/js/jquery-2.2.3.min.js"></script>
	<link href="http://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700" rel="stylesheet">
</head>
<body>
    	<!--/banner-->
	<header>
		<div class="top-bar_sub container-fluid">
			<div class="row">
				<div class="col-md-4 top-forms text-left mt-4"  data-aos="fade-up">
					<span>欢迎回来：{{ request.session.username }}&nbsp&nbsp&nbsp<a href="{% url 'food:logout' %}" style="color:#707173">退出</a></span>
					<span class="mx-lg-4 mx-md-2  mx-1">
						<a href="{% url 'food:login' %}">
							<i class="fas fa-lock"></i>登录</a>
					</span>
					<span>
						<a href="{% url 'food:register' %}">
							<i class="far fa-user"></i> 注册</a>
					</span>
				</div>
				<div class="col-md-4 logo text-center" data-aos="fade-up">
					<a class="navbar-brand" href="{% url 'food:index' %}">
						<i class="fab fa-gitkraken"></i> 蛋糕房</a>
				</div>

				<div class="col-md-4 log-icons text-right"  data-aos="fade-up">

					<ul class="social_list1 mt-4">

						<li>
							<a href="#" class="facebook1 mx-2">
								<i class="fab fa-facebook-f"></i>

							</a>
						</li>
						<li>
							<a href="#" class="twitter2">
								<i class="fab fa-twitter"></i>

							</a>
						</li>
						<li>
							<a href="#" class="dribble3 mx-2">
								<i class="fab fa-dribbble"></i>
							</a>
						</li>
						<li>
							<a href="#" class="pin">
								<i class="fab fa-pinterest-p"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</header>

	<!--/banner-->
	{% block top %}

	{% endblock %}
	<!--//banner-->
	<!--/nav-->
	<div class="header_top" id="home">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>


			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mx-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'food:index' %}">首页
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'food:about' %}">介绍</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'food:menu' %}">菜单</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'food:blog' %}">记录</a>
					</li>

					<!--<li class="nav-item dropdown">-->
						<!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"-->
						    <!--aria-expanded="false">-->
							<!--Drop Down-->
						<!--</a>-->
						<!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
								<!--<a class="dropdown-item" href="#"></a>-->
								<!--<a class="dropdown-item" href="{% url 'food:gallery' %}">Gallery</a>-->
								<!--<div class="dropdown-divider"></div>-->
								<!--<a class="dropdown-item" href="404.html">Services</a>-->

						<!--</div>-->
					<!--</li>-->
					<li class="nav-item">
						<a class="nav-link" href="{% url 'food:contact' %}">联系我们</a>
					</li>

				</ul>
			</div>
		</nav>

	</div>
	<!--//nav-->
	<!--<ol class="breadcrumb">-->
		<!--<li class="breadcrumb-item">-->
			<!--<a href="{% url 'food:index' %}">Home</a>-->
		<!--</li>-->
		<!--<li class="breadcrumb-item active">Signin</li>-->
	<!--</ol>-->

        {% block body %} {% endblock %}

	<!--footer-->
	<footer>
		<div class="container">
			<div class="row">
				<!--<div class="col-lg-4 footer-grid text-left" data-aos="fade-right" >-->
					<!--&lt;!&ndash;<h3>About US</h3>&ndash;&gt;-->
					<!--&lt;!&ndash;<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>&ndash;&gt;-->
					<!--<div class="read">-->
						<!--<a href="{% url 'food:error' %}" class="btn btn-primary read-m">Read More</a>-->
					<!--</div>-->
				<!--</div>-->
				<!-- subscribe -->
				<!--<div class="col-lg-8 subscribe-main footer-grid text-left" data-aos="fade-left">-->
					<h2 style="text-align: center; color: #BCBCBC">关于博客 · 联系我们 · 加入我们 · 博客出版 · 品牌与徽标 · 帮助中心 · 合作伙伴 </h2>
					<!--<div class="subscribe-main text-left">-->
						<!--<div class="subscribe-form">-->
							<!--<form action="#" method="post" class="subscribe_form">-->
								<!--<input class="form-control" type="email" placeholder="Enter your email..." required="">-->
								<!--<button type="submit" class="btn btn-primary submit">Submit</button>-->
							<!--</form>-->

						<!--</div>-->
						<!--<p>We respect your privacy.No spam ever!</p>-->
					<!--</div>-->
					<!-- //subscribe -->
					<!--<div class="footer-cpy text-left">-->
						<!--<div class="copyrighttop">-->
							<!--<ul>-->
								<!--<li class="mx-lg-3 mx-md-2 mx-1">-->
									<!--<a class="facebook" href="#">-->
										<!--<i class="fab fa-facebook-f"></i>-->
										<!--<span>Facebook</span>-->
									<!--</a>-->
								<!--</li>-->
								<!--<li>-->
									<!--<a class="facebook" href="#">-->
										<!--<i class="fab fa-twitter"></i>-->
										<!--<span>Twitter</span>-->
									<!--</a>-->
								<!--</li>-->
								<!--<li class="mx-lg-3 mx-md-2 mx-1">-->
									<!--<a class="facebook" href="#">-->
										<!--<i class="fab fa-google-plus-g"></i>-->
										<!--<span>Google+</span>-->
									<!--</a>-->
								<!--</li>-->
								<!--<li>-->
									<!--<a class="facebook" href="#">-->
										<!--<i class="fab fa-pinterest-p"></i>-->
										<!--<span>Pinterest</span>-->
									<!--</a>-->
								<!--</li>-->
							<!--</ul>-->
						<!--</div>-->
						<!--<div class="copyrightbottom">-->
							<!--<p>Copyright &copy; 2018.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>-->

						<!--</div>-->
					<!--</div>-->
				<!--</div>-->
			</div>
			<!-- //footer -->
		</div>
	</footer>
	<!---->

	<!-- js -->

	<!-- //js -->
	 <!-- /js files -->
	<link href='/static/css/aos.css' rel='stylesheet prefetch' type="text/css" media="all" />
	<link href='/static/css/aos-animation.css' rel='stylesheet prefetch' type="text/css" media="all" />
	<script src='/static/js/aos.js'></script>
	<script src="/static/js/aosindex.js"></script>
	<!-- //js files -->
	<!--/ start-smoth-scrolling -->
	<script src="/static/js/move-top.js"></script>
	<script src="/static/js/easing.js"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!--// end-smoth-scrolling -->

	<script>
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#home" class="scroll" id="toTop" style="display: block;">
		<span id="toTopHover" style="opacity: 1;"> </span>
	</a>

	<!-- //Custom-JavaScript-File-Links -->
	<script src="/static/js/bootstrap.js"></script>



</body>
</html>

demo3/templates/blog.html
{% extends 'base.html' %}
{% block top %}
<div class="banner-inner"></div>
{% endblock %}
{% block body %}
	<!--/main-->
	<section class="banner-bottom">
		<div class="container">
			<h3 class="tittle">我们的足迹</h3>
			<div class="row inner-sec">
				<div class="col-md-6 banner-btm-left">
					<div class="banner-btm-top">
						<div class="banner-btm-inner a1 text-left">
							<div class="blog_date">

								<h4>Feb.10.2018</h4>

							</div>
							<h6>
								<a href="single.html">二七广场</a>
							</h6>
							<p class="paragraph">当奶油恋上芝士，香浓的爱意沉浸在芝士的丝滑里，却因同根生而被命运阻隔，于是这份爱恋少了些许甜腻，多了一丝酸楚。幸好，有相思豆的铺撒，让原本凄凉的爱情多了无限温暖。</p>

							<a href="{% url 'food:error' %}" class="blog-btn">Know More</a>
						</div>
						<div class="banner-btm-inner a2">

						</div>
					</div>
					<div class="banner-btm-bottom">
						<div class="banner-btm-inner a3">

						</div>
						<div class="banner-btm-inner a4 text-left">
							<div class="blog_date">

								<h4>Feb.18.2019</h4>

							</div>
							<h6>
								<a href="single.html">金山区东三街</a>
							</h6>
							<p class="paragraph">粉红色的蛋糕 来自大自然的鲜明而清新的粉红色,涂抹在可爱的花朵上,还有灿烂的蝴蝶轻轻驻足。不是童话,却胜似童话。讨好味觉的艺术得到了淋漓尽致的发挥.</p>

							<a href="{% url 'food:error' %}" class="blog-btn">Know More</a>
						</div>
					</div>
				</div>
				<div class="col-md-6 banner-btm-left">
					<div class="banner-btm-top">
						<div class="banner-btm-inner a1 text-left">
							<div class="blog_date">

								<h4>Aug.05.2017</h4>

							</div>
							<h6>
								<a href="single.html">文化路英才街</a>
							</h6>
							<p class="paragraph">香浓细滑的巧克力和奶油，再加上酥脆的姜饼干，口感丰富层次鲜明。搭配上一杯清甜的果香红茶，清新的口感，迷人的色泽、馥郁的水果香，马上让你心旷神怡，唇齿留香。</p>
							<div class="clearfix"></div>
							<a href="{% url 'food:error' %}" class="blog-btn">Know More</a>
						</div>
						<div class="banner-btm-inner a5">

						</div>
					</div>
					<div class="banner-btm-bottom">
						<div class="banner-btm-inner a6">

						</div>
						<div class="banner-btm-inner a4 text-left">
							<div class="blog_date">

								<h4>Jan.11.2016</h4>

							</div>
							<h6>
								<a href="single.html">明德路德智街</a>
							</h6>
							<p class="paragraph">全巧克力的蛋糕 它不是最眩、最醒目的，但是总有忠实拥趸对它青睐有加。香浓诱人的巧克力口味;柔软的口感、甜蜜的味道,完美的全巧克力蛋糕经得起各种口味的挑剔.表面富有曲线美的巧克力花纹与蛋糕的名称相得益彰。</p>

							<a href="{% url 'food:error' %}" class="blog-btn">Know More</a>
						</div>
					</div>
				</div>
			 </div>
		</div>
	</section>
	<!--//main-->
{% endblock %}

demo3/templates/contact.html
{% extends 'base.html' %}
{% block top %}
<div class="banner-inner"></div>
{% endblock %}
{% block body %}
	<!--/main-->
	<section class="banner-bottom">
		<h2 style="color: darkred; text-align: center " >{{ msg }}</h2>
		<h3 class="tittle">联系我们</h3>
		<p class="sub text-center">我们喜欢讨论你的想法</p>
		<div class="ad-inf-sec">
			<div class="container">
				<div class="address row">

					<div class="col-lg-4 address-grid" data-aos="zoom-in">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="far fa-map"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>地址</h6>
								<p>address：红旗路东三街108号</p>
							</div>
						</div>

					</div>
					<div class="col-lg-4 address-grid" data-aos="zoom-in">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="far fa-envelope"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>邮箱</h6>
								<p>Email :
									<a href="mailto:example@email.com"> zk161162@163.com</a>
								</p>
							</div>

						</div>
					</div>
					<div class="col-lg-4 address-grid" data-aos="zoom-in">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="fas fa-mobile-alt"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>电话：</h6>
								<p>phone：010-3612660835</p>

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="contact_grid_right">
				<form action="{% url 'food:contact' %}" method="post">
					{% csrf_token %}
					<div class="row contact_left_grid">
						<div class="col-md-6 con-left">
							<div class="form-group" data-aos="fade-down">
								<label for="validationCustom01 my-2">用户名</label>
								<input class="form-control" type="text" name="Name" disabled placeholder="{{ request.session.username }}" value="{{ request.session.username }}" required="">
							</div>
							<div class="form-group" data-aos="fade-down">
								<label for="exampleFormControlInput1">邮箱</label>
								<input class="form-control" type="email" name="Email" placeholder="" required="">
							</div>
							<div class="form-group" data-aos="fade-down">
								<label for="validationCustom03 my-2">建议</label>
								<input class="form-control" type="text" name="Subject" placeholder="" required="">
							</div>
						</div>
						<div class="col-md-6 con-right">
							<div class="form-group" data-aos="fade-down">
								<label for="textarea">详细</label>
								<textarea id="textarea" name="Detail" placeholder=""></textarea>
							</div>
							<h3 id="tip1"></h3>
							{% if request.session.username %}
								<input class="form-control"  type="submit"  value="Submit">
								<a href="" class="form-control" hidden> Submit </a>
							{% else %}
								<input class="form-control"  type="submit" hidden value="Submit">
								<a href="{% url 'food:text' %}" class="form-control"> Submit </a>
							{% endif %}
						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
	<!--//main-->
<script>

//	$('#tip').on('click',function () {
//		let $session = $('#ses').val();
//		// alert($session);
//		console.log($session)
//	})
	// 	$.ajax({
	// 		url:'/Foods/contact/',
	// 		data:{'temp':123},
	// 		type:'GET',
	// 		dateType:'json',
	// 		success (data) {
	// 			if(data.issuccess){
	// 				$('#tip1').innerText='请先登录！'
	// 			}
	// 			else {
	// 				$('#tip1').empty()
	// 			}
	// 		}
	// 	})
	// });

</script>
{% endblock %}